version: "3.8"
services:
  postgres:
    container_name: "dpb_postgres"
    image: "postgres:12"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5444:5432
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "hid_d3n."

volumes:
  postgres-data:
    driver: local
